version: 2

jobs:
  linux:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run: swift build -c release
      - run: swift test -c release
  linux-release:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
